### ISSUE TITLE
ERROR in ./scripts/views/Status/styles.scss

### ISSUE THREAD

**Issue by windyboy** [jimzhan/generator-alt#1]
'npm start' gets error message

`Module parse failed: scripts/views/Status/styles.scss Line 1: Unexpected token .`

npm -v
2.13.0

node -v
v0.12.7

**Comment by jimzhan** [comment]
I've also switched to your version to test & it works fine. 
It's the `yo alt` installation successfully downloaded all libs? 
Or have you changed webpack.config.js?

**Comment by windyboy** [comment]
yo alt finished with no error
no errors in npm install command.
If I choose Less, the same error message as above.
But when I choose Sass, every thing is ok, no error message.
It looks like Less script not work.

**Comment by jimzhan** [comment]
@windyboy I've just published version 0.2.4, it should be fixed now. Could you help check that again?

**Comment by windyboy** [comment]
@jimzhan The patch works! Less script works fine just as Sass.

**Comment by jimzhan** [comment]
@windyboy Thanks for posting the issue and debugging :-)
